/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generate sidebar from the parent tech-notes directory (path is set in docusaurus.config)
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;


